### ISSUE TITLE
Environment variable RUNTIME_LOG_LEVEL when set to 1 does not show runtime's trace 

### ISSUE THREAD

**Issue by x3c41a** [open-web3-stack/polkadot-ecosystem-tests#114]
Steps to reproduce:
I run ecosystem-tests with the following .env file: 
```
LOG_LEVEL=debug # keep debug level to filter out most of chopsticks logs, ports and wasm info is still there
RUNTIME_LOG_LEVEL=1 # 1 or trace
DB_PATH=./db.sqlite
ASSETHUBPOLKADOT_WASM=./asset_hub_polkadot_runtime.compact.compressed.wasm
ASTAR_WASM=./astar_runtime.compact.compressed.wasm
```

There are no trace logs from the runtime, e.g. 
```
 xcm::execute  TRACE: Executing message origin=Location { parents: 0, interior: X1([Parachain(1000)]) } message=Xcm([ReceiveTeleportedAsset(Assets([Asset { id: AssetId(Location { parents: 0, interior: Here }), fun: Fungible(7000000000000) }])), PayFees { asset: Asset { id: AssetId(Location { parents: 0, interior: Here }), fun: Fungible(7000000000000) } }, ReceiveTeleportedAsset(Assets([])), ClearOrigin, PayFees { asset: Asset { id: AssetId(Location { parents: 0, interior: Here }), fun: Fungible(400000000000) } }, SetTopic([77, 56, 17, 205, 139, 97, 6, 202, 171, 215, 147, 248, 255, 56, 159, 159, 159, 135, 14, 136, 122, 237, 73, 201, 158, 93, 209, 78, 156, 226, 168, 204])]) weight_credit=Weight { ref_time: 0, proof_size: 0 }
 ```
The only log that runtime displays is the final error, like `NotHoldingFees` or `Message Unroutable`. 

I was able to reproduce the same XCM program with local wasms and chopsticks, and all the trace logs were there.
It might be that environment variables are not propagated...

**Comment by xlc** [comment]
Just found out the level doc in readme is wrong. trace is 5 not 1.
And make sure the wasm is built with logging enabled

**Comment by x3c41a** [comment]
I built wasm with the `--release` flag and set `RUNTIME_LOG_LEVEL` to 5. After that I was able to see the runtime log for Polkadot Asset Hub. 

Thanks for looking into that issue! I also left a minor comment on the PR.
