### ISSUE TITLE
KNOWN_GOOD_BLOCK_NUMBERS.env

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/polkadot-ecosystem-tests#4]
Have a `KNOWN_GOOD_BLOCK_NUMBERS.env` that is generated with `update-env` format.
Setup GH action run every 6 hours, using latest block number, and if all tests passed, update `KNOWN_GOOD_BLOCK_NUMBERS.env` to the bock number used in tests. Commit and push the change.

Provide a yarn script to update it to the latest value.

When running tests for new PR, loads `KNOWN_GOOD_BLOCK_NUMBERS.env`. This ensures the PR won't be impacted by new changes in the networks. The RP author can manually bump the block numbers with the provided script if needed.

**Comment by bkchr** [comment]
> and if all tests passed,

I assume that otherwise it will create an issue or similar and inform us?

**Comment by xlc** [comment]
Yes https://github.com/open-web3-stack/e2e-test/issues/5 will be used to notify people
