### ISSUE TITLE
Notification System

### ISSUE THREAD

**Issue by xlc** [open-web3-stack/polkadot-ecosystem-tests#5]
When a test failed on master, we should notify relevant teams without spam them.

In config.yml file, we should specify an issue number for each network.
When a test on master failed, we should identify which networks are related and write a comment to the network issue with link to the failed action and other helpful info like test name, block number, error message etc.

The network team can watch issues without watch the whole repo.

**Comment by bkchr** [comment]
I would have thought that the teams can just put down people to ping in the `config.yml`, but what you describe should also work.

**Comment by xlc** [comment]
people need to submit PR to add their name. it is easier to just click the subscribe button of an issue
